# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Duncans Functions AWS"
client_id = "4d3d13c96a2cd9aee42da25c5c45db97"
application_url = "https://main.d2vg61wh9jjjw7.amplifyapp.com"
scopes = "read_customers,write_customers,read_inventory,read_orders,read_all_orders,write_orders,read_products,write_products,read_product_listings,read_reports,read_shipping,write_assigned_fulfillment_orders,read_assigned_fulfillment_orders,write_fulfillments,read_fulfillments,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_third_party_fulfillment_orders,write_third_party_fulfillment_orders,read_discounts,write_discounts,write_store_credit_account_transactions"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "puzzles-galore-shop.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,read_inventory,read_orders,read_all_orders,write_orders,read_products,write_products,read_product_listings,read_reports,read_shipping,write_assigned_fulfillment_orders,read_assigned_fulfillment_orders,write_fulfillments,read_fulfillments,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_third_party_fulfillment_orders,write_third_party_fulfillment_orders,read_discounts,write_discounts,write_store_credit_account_transactions"

[webhooks]
api_version = "2025-01"

[auth]
# Update this to match the URL in your Partner Dashboard
redirect_urls = [
  "https://main.d2vg61wh9jjjw7.amplifyapp.com/auth/callback",
  "https://main.d2vg61wh9jjjw7.amplifyapp.com/api/auth/callback"
]



# Remove this targeting if it's causing conflicts
# [[extensions.targeting]]
# target = "admin.order-items.item-column.render-after"
# module = "/extensions/inventory-display/src/index.js"
